name: Verify tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master    

jobs:
  execute_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: run tests
        run: |
          npm install
          npm test